// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bOVQPOOQeQQOOOVQPO'#CrOOQO'#Cb'#CbOmQQO'#CaOOQO'#Cq'#CqOVQPO,58xOVQPO,58xOrQQO,59^O!`QQO,58{OOQO1G.d1G.dO!gQQO1G.dOOQO1G.x1G.xOOQO'#Cu'#CuO}QQO'#CvOOQO'#Cg'#CgOOQO1G.g1G.gO!uQQO'#CkOOQO'#Cl'#ClO#^QQO,59bO}QQO'#CmO#eQQO,59VOOQO-E6j-E6jOOQO1G.|1G.|OOQO,59X,59XOOQO-E6k-E6k",
  stateData: '#|~OdOS~OVROWROXROgQO~ORUOSVO~OYXO~ORUOSVOh[O~OW]OX]O[]O]]O^]O~Og^O~P}ORUOSQibQihQi~OkdOW_XX_X[_X]_X^_Xh_X~OhgO~P}OkdOW_aX_a[_a]_a^_ah_a~O',
  goto: '!vkPPlPPlrPPPPxPPP{!P!VPPP!]lPP!i!sXTOQUVXSOQUVR`XTb^cQc^RfcQeaRieQPOQWQQYURZVQ_XSa^cRhdR_X',
  nodeNames: '⚠ Query ConditionGroup And Or Condition Property UnquotedString SingleQuotedString DoubleQuotedString Comparator Value Number Boolean Null List',
  maxTerm: 27,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "8R~Rwpq#lqr#qrs$Stu#}wx%vxy'jyz'o|}'t!Q!['y!^!_(R!_!`#}!`!a(R!c!d(Z!d!h(r!h!i*P!i!k(r!k!l,a!l!p(r!p!q-]!q!r/_!r!v(r!v!w0Z!w!}(r#O#P1Z#Q#R#}#T#U1g#U#Y(r#Y#Z2g#Z#](r#]#^4d#^#b(r#b#c4{#c#d6j#d#h(r#h#i7R#i#o(r#r#s#}#t;'S(r<%lO(r~#qOd~Q#tRtu#}!_!`#}#Q#R#}Q$SOYQ~$VWOY$SZr$Srs$os#O$S#O#P$t#P;'S$S;'S;=`%p<%lO$S~$tOX~~$wRO;'S$S;'S;=`%Q;=`O$S~%TXOY$SZr$Srs$os#O$S#O#P$t#P;'S$S;'S;=`%p;=`<%l$S<%lO$S~%sP;=`<%l$S~%yWOY%vZw%vwx&cx#O%v#O#P&h#P;'S%v;'S;=`'d<%lO%v~&hOW~~&kRO;'S%v;'S;=`&t;=`O%v~&wXOY%vZw%vwx&cx#O%v#O#P&h#P;'S%v;'S;=`'d;=`<%l%v<%lO%v~'gP;=`<%l%v~'oOg~~'tOh~~'yOk~~(OP[~!Q!['yQ(WPYQ!_!`#}R(`UVP!c!p(r!p!q)T!q!}(r#T#o(r#t;'S(r<%lO(rP(wSVP!c!}(r#T#o(r#t;'S(r<%lO(rR)YUVP!c!f(r!f!g)l!g!}(r#T#o(r#t;'S(r<%lO(rR)sSRQVP!c!}(r#T#o(r#t;'S(r<%lO(rR*UTVP!c!d*e!d!}(r#T#o(r#t;'S(r<%lO(rR*jUVP!c!n(r!n!o*|!o!}(r#T#o(r#t;'S(r<%lO(rR+RUVP!c!u(r!u!v+e!v!}(r#T#o(r#t;'S(r<%lO(rR+jUVP!c!g(r!g!h+|!h!}(r#T#o(r#t;'S(r<%lO(rR,TS]QVP!c!}(r#T#o(r#t;'S(r<%lO(rR,fUVP!c!p(r!p!q,x!q!}(r#T#o(r#t;'S(r<%lO(rR-PSYQVP!c!}(r#T#o(r#t;'S(r<%lO(rR-bWVP!c!k(r!k!l,a!l!w(r!w!x-z!x!}(r#T#o(r#t;'S(r<%lO(rR.PUVP!c!n(r!n!o.c!o!}(r#T#o(r#t;'S(r<%lO(rR.hUVP!c!n(r!n!o.z!o!}(r#T#o(r#t;'S(r<%lO(rR/RS^QVP!c!}(r#T#o(r#t;'S(r<%lO(rR/dUVP!c!t(r!t!u/v!u!}(r#T#o(r#t;'S(r<%lO(rR/}SSQVP!c!}(r#T#o(r#t;'S(r<%lO(rR0`UVP!c!t(r!t!u0r!u!}(r#T#o(r#t;'S(r<%lO(rR0wUVP!c!w(r!w!x+e!x!}(r#T#o(r#t;'S(r<%lO(r~1^R#b#c#l#f#g#l#h#i#lR1lUVP!c!}(r#T#b(r#b#c2O#c#o(r#t;'S(r<%lO(rR2TUVP!c!}(r#T#W(r#W#X)l#X#o(r#t;'S(r<%lO(rR2lTVP!c!}(r#T#U2{#U#o(r#t;'S(r<%lO(rR3QUVP!c!}(r#T#`(r#`#a3d#a#o(r#t;'S(r<%lO(rR3iUVP!c!}(r#T#g(r#g#h3{#h#o(r#t;'S(r<%lO(rR4QUVP!c!}(r#T#X(r#X#Y+|#Y#o(r#t;'S(r<%lO(rR4iUVP!c!}(r#T#b(r#b#c,x#c#o(r#t;'S(r<%lO(rR5QWVP!c!}(r#T#](r#]#^4d#^#i(r#i#j5j#j#o(r#t;'S(r<%lO(rR5oUVP!c!}(r#T#`(r#`#a6R#a#o(r#t;'S(r<%lO(rR6WUVP!c!}(r#T#`(r#`#a.z#a#o(r#t;'S(r<%lO(rR6oUVP!c!}(r#T#f(r#f#g/v#g#o(r#t;'S(r<%lO(rR7WUVP!c!}(r#T#f(r#f#g7j#g#o(r#t;'S(r<%lO(rR7oUVP!c!}(r#T#i(r#i#j3{#j#o(r#t;'S(r<%lO(r",
  tokenizers: [0, 1],
  topRules: { 'Query':[0, 1] },
  tokenPrec: 0,
});
