// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';

export const parser = LRParser.deserialize({
  version: 14,
  states: "$bOVQPOOQeQQOOOVQPO'#CrOOQO'#Cb'#CbOmQQO'#CaOOQO'#Cq'#CqOVQPO,58xOVQPO,58xOrQQO,59^O!`QQO,58{OOQO1G.d1G.dO!gQQO1G.dOOQO1G.x1G.xOOQO'#Cu'#CuO}QQO'#CvOOQO'#Cg'#CgOOQO1G.g1G.gO!uQQO'#CkOOQO'#Cl'#ClO#^QQO,59bO}QQO'#CmO#eQQO,59VOOQO-E6j-E6jOOQO1G.|1G.|OOQO,59X,59XOOQO-E6k-E6k",
  stateData: '#|~OdOS~OVROWROXROgQO~ORUOSVO~OYXO~ORUOSVOh[O~OW]OX]O[]O]]O^]O~Og^O~P}ORUOSQibQihQi~OkdOW_XX_X[_X]_X^_Xh_X~OhgO~P}OkdOW_aX_a[_a]_a^_ah_a~O',
  goto: '!vkPPlPPlrPPPPxPPP{!P!VPPP!]lPP!i!sXTOQUVXSOQUVR`XTb^cQc^RfcQeaRieQPOQWQQYURZVQ_XSa^cRhdR_X',
  nodeNames: '⚠ Query ConditionGroup And Or Condition Property UnquotedString SingleQuotedString DoubleQuotedString Comparator Value Number Boolean Null List',
  maxTerm: 27,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "8[~RzXY#uYZ#u]^#upq#uqr#zrs$]tu$Wwx&Pxy'syz'x|}'}!Q![(S!^!_([!_!`$W!`!a([!c!d(d!d!h({!h!i*Y!i!k({!k!l,j!l!p({!p!q-f!q!r/h!r!v({!v!w0d!w!}({#O#P1d#Q#R$W#T#U1p#U#Y({#Y#Z2p#Z#]({#]#^4m#^#b({#b#c5U#c#d6s#d#h({#h#i7[#i#o({#r#s$W#t;'S({<%lO({~#zOd~Q#}Rtu$W!_!`$W#Q#R$WQ$]OYQ~$`WOY$]Zr$]rs$xs#O$]#O#P$}#P;'S$];'S;=`%y<%lO$]~$}OX~~%QRO;'S$];'S;=`%Z;=`O$]~%^XOY$]Zr$]rs$xs#O$]#O#P$}#P;'S$];'S;=`%y;=`<%l$]<%lO$]~%|P;=`<%l$]~&SWOY&PZw&Pwx&lx#O&P#O#P&q#P;'S&P;'S;=`'m<%lO&P~&qOW~~&tRO;'S&P;'S;=`&};=`O&P~'QXOY&PZw&Pwx&lx#O&P#O#P&q#P;'S&P;'S;=`'m;=`<%l&P<%lO&P~'pP;=`<%l&P~'xOg~~'}Oh~~(SOk~~(XP[~!Q![(SQ(aPYQ!_!`$WR(iUVP!c!p({!p!q)^!q!}({#T#o({#t;'S({<%lO({P)QSVP!c!}({#T#o({#t;'S({<%lO({R)cUVP!c!f({!f!g)u!g!}({#T#o({#t;'S({<%lO({R)|SRQVP!c!}({#T#o({#t;'S({<%lO({R*_TVP!c!d*n!d!}({#T#o({#t;'S({<%lO({R*sUVP!c!n({!n!o+V!o!}({#T#o({#t;'S({<%lO({R+[UVP!c!u({!u!v+n!v!}({#T#o({#t;'S({<%lO({R+sUVP!c!g({!g!h,V!h!}({#T#o({#t;'S({<%lO({R,^S]QVP!c!}({#T#o({#t;'S({<%lO({R,oUVP!c!p({!p!q-R!q!}({#T#o({#t;'S({<%lO({R-YSYQVP!c!}({#T#o({#t;'S({<%lO({R-kWVP!c!k({!k!l,j!l!w({!w!x.T!x!}({#T#o({#t;'S({<%lO({R.YUVP!c!n({!n!o.l!o!}({#T#o({#t;'S({<%lO({R.qUVP!c!n({!n!o/T!o!}({#T#o({#t;'S({<%lO({R/[S^QVP!c!}({#T#o({#t;'S({<%lO({R/mUVP!c!t({!t!u0P!u!}({#T#o({#t;'S({<%lO({R0WSSQVP!c!}({#T#o({#t;'S({<%lO({R0iUVP!c!t({!t!u0{!u!}({#T#o({#t;'S({<%lO({R1QUVP!c!w({!w!x+n!x!}({#T#o({#t;'S({<%lO({~1gR#b#c#u#f#g#u#h#i#uR1uUVP!c!}({#T#b({#b#c2X#c#o({#t;'S({<%lO({R2^UVP!c!}({#T#W({#W#X)u#X#o({#t;'S({<%lO({R2uTVP!c!}({#T#U3U#U#o({#t;'S({<%lO({R3ZUVP!c!}({#T#`({#`#a3m#a#o({#t;'S({<%lO({R3rUVP!c!}({#T#g({#g#h4U#h#o({#t;'S({<%lO({R4ZUVP!c!}({#T#X({#X#Y,V#Y#o({#t;'S({<%lO({R4rUVP!c!}({#T#b({#b#c-R#c#o({#t;'S({<%lO({R5ZWVP!c!}({#T#]({#]#^4m#^#i({#i#j5s#j#o({#t;'S({<%lO({R5xUVP!c!}({#T#`({#`#a6[#a#o({#t;'S({<%lO({R6aUVP!c!}({#T#`({#`#a/T#a#o({#t;'S({<%lO({R6xUVP!c!}({#T#f({#f#g0P#g#o({#t;'S({<%lO({R7aUVP!c!}({#T#f({#f#g7s#g#o({#t;'S({<%lO({R7xUVP!c!}({#T#i({#i#j4U#j#o({#t;'S({<%lO({",
  tokenizers: [0, 1],
  topRules: { Query: [0, 1] },
  tokenPrec: 0,
});
