nodeLinker: node-modules

enableGlobalCache: false

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  ixsystems:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN}"

compressionLevel: mixed

defaultSemverRangePrefix: "~"

enableImmutableInstalls: false

enableTelemetry: false

enableProgressBars: true

installStatePath: .yarn/install-state.gz

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard