nodeLinker: pnp

pnpMode: strict

pnpEnableEsmLoader: true

enableGlobalCache: true

npmRegistryServer: "https://registry.npmjs.org"

compressionLevel: mixed

defaultSemverRangePrefix: "~"

enableImmutableInstalls: false

enableTelemetry: false

enableProgressBars: true

installStatePath: .yarn/install-state.gz

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard