github_checks:
  annotations: false
coverage:
  status:
    patch:
      default:
        target: 50%
        base: auto
        informational: true
    project:
      default:
        informational: true
