github_checks:
  annotations: false
ignore:
  - "**/*.module.ts"
  - "**/*.routing.ts"
coverage:
  status:
    patch:
      default:
        target: 50%
        base: auto
    project:
      default:
        informational: true
