export interface AdvancedConfig {
  advancedmode: boolean;
  anonstats: boolean;
  anonstats_token: string;
  autotune: boolean;
  boot_scrub: number;
  consolemenu: boolean;
  consolemsg: boolean;
  debugkernel: boolean;
  fqdn_syslog: boolean;
  id: number;
  isolated_gpu_pci_ids: string[];
  kdump_enabled: boolean;
  motd: string;
  overprovision: number;
  powerdaemon: boolean;
  sed_user: string;
  serialconsole: boolean;
  serialport: string;
  serialspeed: string;
  swapondrive: number;
  syslog_tls_certificate: number;
  syslog_transport: string;
  sysloglevel: string;
  syslogserver: string;
  traceback: boolean;
  uploadcrash: boolean;
  sed_passwd: string;
}
