export interface FtpConfig {
  anonpath: string;
  anonuserbw: number;
  anonuserdlbw: number;
  banner: string;
  clients: number;
  defaultroot: boolean;
  dirmask: string;
  filemask: string;
  fxp: boolean;
  id: number;
  ident: boolean;
  ipconnections: number;
  localuserbw: number;
  localuserdlbw: number;
  loginattempt: number;
  masqaddress: string;
  onlyanonymous: boolean;
  onlylocal: boolean;
  options: string;
  passiveportsmax: number;
  passiveportsmin: number;
  port: number;
  resume: boolean;
  reversedns: boolean;
  ssltls_certificate: number;
  timeout: number;
  timeout_notransfer: number;
  tls: boolean;
  tls_opt_allow_client_renegotiations: boolean;
  tls_opt_allow_dot_login: boolean;
  tls_opt_allow_per_user: boolean;
  tls_opt_common_name_required: boolean;
  tls_opt_dns_name_required: boolean;
  tls_opt_enable_diags: boolean;
  tls_opt_export_cert_data: boolean;
  tls_opt_ip_address_required: boolean;
  tls_opt_no_empty_fragments: boolean;
  tls_opt_no_session_reuse_required: boolean;
  tls_opt_stdenvvars: boolean;
  tls_policy: string;
}

export type FtpConfigUpdate = Omit<FtpConfig, 'id'>;
