import { SshConnectionsSetupMethod } from 'app/enums/ssh-connections-setup-method.enum';
import { SshCredentials } from 'app/interfaces/ssh-credentials.interface';

/**
 * Params for `keychaincredential.setup_ssh_connection`.
 *
 * Shaped as middleware declares it: the setup type selects which block is
 * required, and a private key is either generated by name or an existing one
 * by id. Loosening either union back to optionals compiles against the
 * legacy directory but not against the typed client.
 */
export type SshConnectionSetup = SshConnectionManualSetup | SshConnectionSemiAutomaticSetup;

export type SshConnectionSetupPrivateKey
  = | { generate_key: true; name: string }
    | { generate_key: false; existing_key_id: number };

interface SshConnectionSetupBase {
  connection_name: string;
  private_key: SshConnectionSetupPrivateKey;
}

export interface SshConnectionManualSetup extends SshConnectionSetupBase {
  setup_type: SshConnectionsSetupMethod.Manual;
  manual_setup: SshCredentials;
}

export interface SshConnectionSemiAutomaticSetup extends SshConnectionSetupBase {
  setup_type: SshConnectionsSetupMethod.SemiAutomatic;
  semi_automatic_setup: {
    url: string;
    admin_username: string;
    password: string;
    username: string;
    connect_timeout: number;
    token?: string;
    otp_token?: string;
    sudo?: boolean;
    verify_ssl?: boolean;
  };
}

export interface RemoteSshScanParams {
  connect_timeout?: number;
  host: string;
  port: number;
}
