import { CallParams, v27_0_0 } from '@truenas/api-client';
import { WebUiApiDirectory } from 'app/modules/websocket/typed-api/typed-api-client.token';

/**
 * Params for `keychaincredential.setup_ssh_connection`, as middleware declares
 * them: the setup type selects which block is required, and a private key is
 * either generated by name or an existing one by id.
 */
export type SshConnectionSetup = CallParams<WebUiApiDirectory, 'keychaincredential.setup_ssh_connection'>[0];

export type SshConnectionManualSetup = v27_0_0.SetupSSHConnectionManual;

export type SshConnectionSemiAutomaticSetup = v27_0_0.SetupSSHConnectionSemiautomatic;

export type SshConnectionSetupPrivateKey = SshConnectionSetup['private_key'];

export type RemoteSshScanParams = v27_0_0.KeychainCredentialRemoteSshHostKeyScanArgs;
