import { HarnessLoader } from '@angular/cdk/testing';
import { TestbedHarnessEnvironment } from '@angular/cdk/testing/testbed';
import { Spectator } from '@ngneat/spectator';
import { createComponentFactory, mockProvider } from '@ngneat/spectator/jest';
import {
  TnButtonHarness, TnMenuHarness, TnMenuTesting, TnTableHarness,
} from '@truenas/ui-components';
import { MockComponent } from 'ng-mocks';
import { fakeSuccessfulJob } from 'app/core/testing/utils/fake-job.utils';
import {
  mockApi, mockCall, mockJob,
} from 'app/core/testing/utils/mock-api.utils';
import { mockAuth } from 'app/core/testing/utils/mock-auth.utils';
import { ConfirmDeleteJobOptions } from 'app/interfaces/dialog.interface';
import { Tunable } from 'app/interfaces/tunable.interface';
import { DialogService } from 'app/modules/dialog/dialog.service';
import { BasicSearchComponent } from 'app/modules/forms/search-input/components/basic-search/basic-search.component';
import { PageHeaderComponent } from 'app/modules/page-header/page-title-header/page-header.component';
import { FormSidePanelService } from 'app/modules/slide-ins/form-side-panel/form-side-panel.service';
import { SlideInResult } from 'app/modules/slide-ins/slide-in-result';
import { ApiService } from 'app/modules/websocket/api.service';
import { TunableListComponent } from 'app/pages/system/advanced/tunable/tunable-list/tunable-list.component';

describe('TunableListComponent', () => {
  let spectator: Spectator<TunableListComponent>;
  let loader: HarnessLoader;
  let table: TnTableHarness;

  const tunables = [
    {
      id: 1,
      type: 'ZFS',
      var: 'zfs_dirty_data_max_max',
      value: '12884901888',
      orig_value: '4294967296',
      comment: 'Generated by autotune',
      enabled: true,
    },
    {
      id: 2,
      type: 'ZFS',
      var: 'zfs_arc_max',
      value: '121227934924',
      orig_value: '0',
      comment: 'Generated by autotune',
      enabled: true,
    },
    {
      id: 3,
      type: 'ZFS',
      var: 'l2arc_noprefetch',
      value: '0',
      orig_value: '1',
      comment: 'Generated by autotune',
      enabled: true,
    },
    {
      id: 4,
      type: 'ZFS',
      var: 'l2arc_write_max',
      value: '10000000',
      orig_value: '8388608',
      comment: 'Generated by autotune',
      enabled: true,
    },
    {
      id: 5,
      type: 'ZFS',
      var: 'l2arc_write_boost',
      value: '40000000',
      orig_value: '8388608',
      comment: 'Generated by autotune',
      enabled: true,
    },
    {
      id: 6,
      type: 'ZFS',
      var: 'zfs_vdev_sync_write_max_active',
      value: '67108864',
      orig_value: '10',
      comment: 'Generated by autotune',
      enabled: true,
    },
    {
      id: 12,
      type: 'SYSCTL',
      var: 'kernel.hostname',
      value: 'truenas',
      orig_value: 'truenas',
      comment: 'Description text',
      enabled: true,
    },
    {
      id: 13,
      type: 'SYSCTL',
      var: 'kernel.watchdog',
      value: '1',
      orig_value: '1',
      comment: 'Woof woof',
      enabled: true,
    },
  ] as Tunable[];

  const createComponent = createComponentFactory({
    component: TunableListComponent,
    imports: [
      MockComponent(PageHeaderComponent),
      BasicSearchComponent,
    ],
    providers: [
      mockProvider(FormSidePanelService, {
        openForm: jest.fn(() => SlideInResult.empty()),
      }),
      mockProvider(DialogService, {
        confirmDelete: jest.fn((options: ConfirmDeleteJobOptions) => options.job()),
      }),
      mockApi([
        mockCall('core.get_jobs'),
        mockCall('tunable.query', tunables),
        mockJob('tunable.delete', fakeSuccessfulJob()),
      ]),
      mockAuth(),
    ],
  });

  async function openRowMenu(uniqueRowTag: string): Promise<TnMenuHarness> {
    spectator.click(spectator.query(`[data-test="button-${uniqueRowTag}-more-action"]`) as HTMLElement);
    return TnMenuTesting.rootLoader(spectator.fixture).getHarness(TnMenuHarness);
  }

  beforeEach(async () => {
    spectator = createComponent();
    loader = TestbedHarnessEnvironment.loader(spectator.fixture);
    table = await loader.getHarness(TnTableHarness);
  });

  it('should show table rows', async () => {
    expect(await table.getHeaderTexts()).toEqual(['Variable', 'Value', 'Type', 'Description', 'Enabled', '']);
    expect(await table.getAllRowTexts()).toEqual([
      ['kernel.hostname', 'truenas', 'SYSCTL', 'Description text', 'Yes', ''],
      ['kernel.watchdog', '1', 'SYSCTL', 'Woof woof', 'Yes', ''],
      ['l2arc_noprefetch', '0', 'ZFS', 'Generated by autotune', 'Yes', ''],
      ['l2arc_write_boost', '40000000', 'ZFS', 'Generated by autotune', 'Yes', ''],
      ['l2arc_write_max', '10000000', 'ZFS', 'Generated by autotune', 'Yes', ''],
      ['zfs_arc_max', '121227934924', 'ZFS', 'Generated by autotune', 'Yes', ''],
      ['zfs_dirty_data_max_max', '12884901888', 'ZFS', 'Generated by autotune', 'Yes', ''],
      ['zfs_vdev_sync_write_max_active', '67108864', 'ZFS', 'Generated by autotune', 'Yes', ''],
    ]);
  });

  it('opens the Add Tunable form when Add is pressed', async () => {
    const addButton = await loader.getHarness(TnButtonHarness.with({ label: 'Add' }));
    await addButton.click();

    expect(spectator.inject(FormSidePanelService).openForm).toHaveBeenCalledWith(expect.anything(), {
      title: 'Add Tunable',
    });
  });

  it('opens the Edit Tunable form with the selected row when Edit is pressed', async () => {
    const menu = await openRowMenu('tunable-kernel-hostname-truenas');
    await menu.clickItem({ label: 'Edit' });

    expect(spectator.inject(FormSidePanelService).openForm).toHaveBeenCalledWith(
      expect.anything(),
      {
        title: 'Edit Tunable (SYSCTL)',
        editData: tunables[6],
      },
    );
  });

  it('shows confirmation when Delete button is pressed', async () => {
    const menu = await openRowMenu('tunable-kernel-hostname-truenas');
    await menu.clickItem({ label: 'Delete' });

    expect(spectator.inject(DialogService).confirmDelete).toHaveBeenCalledWith({
      title: 'Delete Tunable (SYSCTL)',
      message: 'Are you sure you want to delete "kernel.hostname"?',
      job: expect.any(Function),
      jobProgressTitle: 'Deleting...',
      successMessage: 'Tunable "kernel.hostname" deleted',
    });

    expect(spectator.inject(ApiService).job).toHaveBeenCalledWith('tunable.delete', [12]);
  });
});
