import { DiskPowerLevel } from 'app/enums/disk-power-level.enum';
import { DiskStandby } from 'app/enums/disk-standby.enum';
import { EnclosureUi, EnclosureUiSlot } from 'app/interfaces/enclosure.interface';
import { MockEnclosure } from './mock-enclosure-template';

const mockDiskDetail: EnclosureUiSlot = {
  descriptor: 'slot00',
  status: 'OK',
  dev: 'sda',
  pool_info: null,
  name: '',
  size: 1024,
  model: 'model',
  serial: 'serial',
  advpowermgmt: DiskPowerLevel.Disabled,
  togglesmart: false,
  smartoptions: '',
  transfermode: '',
  hddstandby: DiskStandby.Minutes10,
  description: 'description',
  rotationrate: 10,
};

export class MockEs102 extends MockEnclosure {
  readonly totalSlotsFront: number = 102;
  readonly totalSlotsRear: number = 0;
  readonly totalSlotsInternal: number = 0;

  data = {
    name: 'HGST H4102-J 3010',
    model: 'ES102',
    controller: false,
    dmi: 'TRUENAS-M50',
    status: [
      'INFO',
      'CRIT',
    ],
    id: this.enclosureId,
    vendor: 'HGST',
    product: 'H4102-J',
    revision: '3010',
    bsg: '/dev/bsg/19:0:309:0',
    sg: '/dev/sg1155',
    pci: '19:0:309:0',
    rackmount: true,
    top_loaded: true,
    front_slots: 102,
    rear_slots: 0,
    internal_slots: 0,
    elements: {
      'Array Device Slot': {
        1: {
          ...mockDiskDetail,
          descriptor: 'SLOT 000,3FJ28MYT',
          status: 'OK',
          dev: 'sdasv',
          pool_info: null,
        },
        2: {
          ...mockDiskDetail,
          descriptor: 'SLOT 001,3FJBSYXT',
          status: 'OK',
          dev: 'sdasw',
          pool_info: null,
        },
        3: {
          ...mockDiskDetail,
          descriptor: 'SLOT 002,3FJH39PT',
          status: 'OK',
          dev: 'sdasx',
          pool_info: null,
        },
        4: {
          ...mockDiskDetail,
          descriptor: 'SLOT 003,3FJK54HT',
          status: 'OK',
          dev: 'sdasy',
          pool_info: null,
        },
        5: {
          ...mockDiskDetail,
          descriptor: 'SLOT 004,3FJJ1AHT',
          status: 'OK',
          dev: 'sdasz',
          pool_info: null,
        },
        6: {
          ...mockDiskDetail,
          descriptor: 'SLOT 005,3FJJ1GBT',
          status: 'OK',
          dev: 'sdatb',
          pool_info: null,
        },
        7: {
          ...mockDiskDetail,
          descriptor: 'SLOT 006,3FJGYVMT',
          status: 'OK',
          dev: 'sdatc',
          pool_info: null,
        },
        8: {
          ...mockDiskDetail,
          descriptor: 'SLOT 007,3FJJZLZT',
          status: 'OK',
          dev: 'sdatd',
          pool_info: null,
        },
        9: {
          ...mockDiskDetail,
          descriptor: 'SLOT 008,3FJJ36WT',
          status: 'OK',
          dev: 'sdate',
          pool_info: null,
        },
        10: {
          ...mockDiskDetail,
          descriptor: 'SLOT 009,3FJGYL0T',
          status: 'OK',
          dev: 'sdatf',
          pool_info: null,
        },
        11: {
          ...mockDiskDetail,
          descriptor: 'SLOT 010,3FJH3LXT',
          status: 'OK',
          dev: 'sdatg',
          pool_info: null,
        },
        12: {
          ...mockDiskDetail,
          descriptor: 'SLOT 011,3FJKAHTT',
          status: 'OK',
          dev: 'sdath',
          pool_info: null,
        },
        13: {
          ...mockDiskDetail,
          descriptor: 'SLOT 012,3FJGYSKT',
          status: 'OK',
          dev: 'sdati',
          pool_info: null,
        },
        14: {
          ...mockDiskDetail,
          descriptor: 'SLOT 013,3FJK617T',
          status: 'OK',
          dev: 'sdatj',
          pool_info: null,
        },
        15: {
          ...mockDiskDetail,
          descriptor: 'SLOT 014,3FJJ40ET',
          status: 'OK',
          dev: 'sdatw',
          pool_info: null,
        },
        16: {
          ...mockDiskDetail,
          descriptor: 'SLOT 015,3FJGYTRT',
          status: 'OK',
          dev: 'sdatx',
          pool_info: null,
        },
        17: {
          ...mockDiskDetail,
          descriptor: 'SLOT 016,3FJJ1B2T',
          status: 'OK',
          dev: 'sdatk',
          pool_info: null,
        },
        18: {
          ...mockDiskDetail,
          descriptor: 'SLOT 017,3FJJZZBT',
          status: 'OK',
          dev: 'sdatl',
          pool_info: null,
        },
        19: {
          ...mockDiskDetail,
          descriptor: 'SLOT 018,3FJK65VT',
          status: 'OK',
          dev: 'sdatm',
          pool_info: null,
        },
        20: {
          ...mockDiskDetail,
          descriptor: 'SLOT 019,3FJJ1E5T',
          status: 'OK',
          dev: 'sdatn',
          pool_info: null,
        },
        21: {
          ...mockDiskDetail,
          descriptor: 'SLOT 020,3FJKLV8T',
          status: 'OK',
          dev: 'sdato',
          pool_info: null,
        },
        22: {
          ...mockDiskDetail,
          descriptor: 'SLOT 021,3FJJEK3T',
          status: 'OK',
          dev: 'sdatp',
          pool_info: null,
        },
        23: {
          ...mockDiskDetail,
          descriptor: 'SLOT 022,3FJGSEHT',
          status: 'OK',
          dev: 'sdatq',
          pool_info: null,
        },
        24: {
          ...mockDiskDetail,
          descriptor: 'SLOT 023,3FJGT63T',
          status: 'OK',
          dev: 'sdatr',
          pool_info: null,
        },
        25: {
          ...mockDiskDetail,
          descriptor: 'SLOT 024,3FJG59YT',
          status: 'OK',
          dev: 'sdats',
          pool_info: null,
        },
        26: {
          ...mockDiskDetail,
          descriptor: 'SLOT 025,3FJJZMJT',
          status: 'OK',
          dev: 'sdatt',
          pool_info: null,
        },
        27: {
          ...mockDiskDetail,
          descriptor: 'SLOT 026,3FJKLVMT',
          status: 'OK',
          dev: 'sdatu',
          pool_info: null,
        },
        28: {
          ...mockDiskDetail,
          descriptor: 'SLOT 027,3FJ2H3BT',
          status: 'OK',
          dev: 'sdatv',
          pool_info: null,
        },
        29: {
          ...mockDiskDetail,
          descriptor: 'SLOT 028,3FJJ1D2T',
          status: 'OK',
          dev: 'sdaty',
          pool_info: null,
        },
        30: {
          ...mockDiskDetail,
          descriptor: 'SLOT 029,3FJ340KT',
          status: 'OK',
          dev: 'sdatz',
          pool_info: null,
        },
        31: {
          ...mockDiskDetail,
          descriptor: 'SLOT 030,3FJK2B5T',
          status: 'OK',
          dev: 'sdaua',
          pool_info: null,
        },
        32: {
          ...mockDiskDetail,
          descriptor: 'SLOT 031,3FJGSEBT',
          status: 'OK',
          dev: 'sdauu',
          pool_info: null,
        },
        33: {
          ...mockDiskDetail,
          descriptor: 'SLOT 032,3FJGYLGT',
          status: 'OK',
          dev: 'sdaub',
          pool_info: null,
        },
        34: {
          ...mockDiskDetail,
          descriptor: 'SLOT 033,3FJH3L2T',
          status: 'OK',
          dev: 'sdauc',
          pool_info: null,
        },
        35: {
          ...mockDiskDetail,
          descriptor: 'SLOT 034,3FJJ1E7T',
          status: 'OK',
          dev: 'sdaud',
          pool_info: null,
        },
        36: {
          ...mockDiskDetail,
          descriptor: 'SLOT 035,3FJ13ZJT',
          status: 'OK',
          dev: 'sdaue',
          pool_info: null,
        },
        37: {
          ...mockDiskDetail,
          descriptor: 'SLOT 036,3FJGYZ9T',
          status: 'OK',
          dev: 'sdauf',
          pool_info: null,
        },
        38: {
          ...mockDiskDetail,
          descriptor: 'SLOT 037,3FJDR5BT',
          status: 'OK',
          dev: 'sdaug',
          pool_info: null,
        },
        39: {
          ...mockDiskDetail,
          descriptor: 'SLOT 038,3FHTXNXT',
          status: 'OK',
          dev: 'sdaut',
          pool_info: null,
        },
        40: {
          ...mockDiskDetail,
          descriptor: 'SLOT 039,3FJK3ZUT',
          status: 'OK',
          dev: 'sdauh',
          pool_info: null,
        },
        41: {
          ...mockDiskDetail,
          descriptor: 'SLOT 040,3FHZ00AT',
          status: 'OK',
          dev: 'sdaui',
          pool_info: null,
        },
        42: {
          ...mockDiskDetail,
          descriptor: 'SLOT 041,3FJH3KBT',
          status: 'OK',
          dev: 'sdauj',
          pool_info: null,
        },
        43: {
          ...mockDiskDetail,
          descriptor: 'SLOT 042,3FJK00UT',
          status: 'OK',
          dev: 'sdaqx',
          pool_info: null,
        },
        44: {
          ...mockDiskDetail,
          descriptor: 'SLOT 043,3FJGZ28T',
          status: 'OK',
          dev: 'sdauk',
          pool_info: null,
        },
        45: {
          ...mockDiskDetail,
          descriptor: 'SLOT 044,3FJGYUMT',
          status: 'OK',
          dev: 'sdaqy',
          pool_info: null,
        },
        46: {
          ...mockDiskDetail,
          descriptor: 'SLOT 045,3FJ486MT',
          status: 'OK',
          dev: 'sdaul',
          pool_info: null,
        },
        47: {
          ...mockDiskDetail,
          descriptor: 'SLOT 046,3FJK03HT',
          status: 'OK',
          dev: 'sdaum',
          pool_info: null,
        },
        48: {
          ...mockDiskDetail,
          descriptor: 'SLOT 047,3FJ1UGHT',
          status: 'OK',
          dev: 'sdaun',
          pool_info: null,
        },
        49: {
          ...mockDiskDetail,
          descriptor: 'SLOT 048,3FJG5G7T',
          status: 'OK',
          dev: 'sdauo',
          pool_info: null,
        },
        50: {
          ...mockDiskDetail,
          descriptor: 'SLOT 049,3FJH3TST',
          status: 'OK',
          dev: 'sdaup',
          pool_info: null,
        },
        51: {
          ...mockDiskDetail,
          descriptor: 'SLOT 050,3FJJELTT',
          status: 'OK',
          dev: 'sdauq',
          pool_info: null,
        },
        52: {
          ...mockDiskDetail,
          descriptor: 'SLOT 051,3FJKAG5T',
          status: 'OK',
          dev: 'sdaur',
          pool_info: null,
        },
        53: {
          ...mockDiskDetail,
          descriptor: 'SLOT 052,3FJKLVXT',
          status: 'OK',
          dev: 'sdaus',
          pool_info: null,
        },
        54: {
          ...mockDiskDetail,
          descriptor: 'SLOT 053,3FJG5GUT',
          status: 'OK',
          dev: 'sdaqz',
          pool_info: null,
        },
        55: {
          ...mockDiskDetail,
          descriptor: 'SLOT 054,3FJGYZ4T',
          status: 'OK',
          dev: 'sdara',
          pool_info: null,
        },
        56: {
          ...mockDiskDetail,
          descriptor: 'SLOT 055,3FJJZNNT',
          status: 'OK',
          dev: 'sdarb',
          pool_info: null,
        },
        57: {
          ...mockDiskDetail,
          descriptor: 'SLOT 056,3FJGYEMT',
          status: 'OK',
          dev: 'sdarc',
          pool_info: null,
        },
        58: {
          ...mockDiskDetail,
          descriptor: 'SLOT 057,3FJJ750T',
          status: 'OK',
          dev: 'sdard',
          pool_info: null,
        },
        59: {
          ...mockDiskDetail,
          descriptor: 'SLOT 058,3FJJUXJT',
          status: 'OK',
          dev: 'sdare',
          pool_info: null,
        },
        60: {
          ...mockDiskDetail,
          descriptor: 'SLOT 059,3FJGYNZT',
          status: 'OK',
          dev: 'sdarf',
          pool_info: null,
        },
        61: {
          ...mockDiskDetail,
          descriptor: 'SLOT 060,3FHX8YBT',
          status: 'OK',
          dev: 'sdarg',
          pool_info: null,
        },
        62: {
          ...mockDiskDetail,
          descriptor: 'SLOT 061,3FJK2BST',
          status: 'OK',
          dev: 'sdarh',
          pool_info: null,
        },
        63: {
          ...mockDiskDetail,
          descriptor: 'SLOT 062,3FJ2H3AT',
          status: 'OK',
          dev: 'sdari',
          pool_info: null,
        },
        64: {
          ...mockDiskDetail,
          descriptor: 'SLOT 063,3FJG5BMT',
          status: 'OK',
          dev: 'sdarj',
          pool_info: null,
        },
        65: {
          ...mockDiskDetail,
          descriptor: 'SLOT 064,3FHMXXTT',
          status: 'OK',
          dev: 'sdark',
          pool_info: null,
        },
        66: {
          ...mockDiskDetail,
          descriptor: 'SLOT 065,3FJ2NP0T',
          status: 'OK',
          dev: 'sdarl',
          pool_info: null,
        },
        67: {
          ...mockDiskDetail,
          descriptor: 'SLOT 066,3FJGYTET',
          status: 'OK',
          dev: 'sdarm',
          pool_info: null,
        },
        68: {
          ...mockDiskDetail,
          descriptor: 'SLOT 067,3FJK6VNT',
          status: 'OK',
          dev: 'sdarn',
          pool_info: null,
        },
        69: {
          ...mockDiskDetail,
          descriptor: 'SLOT 068,3FJJ1JLT',
          status: 'OK',
          dev: 'sdaro',
          pool_info: null,
        },
        70: {
          ...mockDiskDetail,
          descriptor: 'SLOT 069,3FJJZZ9T',
          status: 'OK',
          dev: 'sdarp',
          pool_info: null,
        },
        71: {
          ...mockDiskDetail,
          descriptor: 'SLOT 070,3FJJ75MT',
          status: 'OK',
          dev: 'sdarq',
          pool_info: null,
        },
        72: {
          ...mockDiskDetail,
          descriptor: 'SLOT 071,3FJJ43MT',
          status: 'OK',
          dev: 'sdarr',
          pool_info: null,
        },
        73: {
          ...mockDiskDetail,
          descriptor: 'SLOT 072,3FHTSB9T',
          status: 'OK',
          dev: 'sdars',
          pool_info: null,
        },
        74: {
          ...mockDiskDetail,
          descriptor: 'SLOT 073,3FJJ3BST',
          status: 'OK',
          dev: 'sdart',
          pool_info: null,
        },
        75: {
          ...mockDiskDetail,
          descriptor: 'SLOT 074,3FJJEL5T',
          status: 'OK',
          dev: 'sdaru',
          pool_info: null,
        },
        76: {
          ...mockDiskDetail,
          descriptor: 'SLOT 075,3FJGYYLT',
          status: 'OK',
          dev: 'sdarv',
          pool_info: null,
        },
        77: {
          ...mockDiskDetail,
          descriptor: 'SLOT 076,3FJJ1JAT',
          status: 'OK',
          dev: 'sdarw',
          pool_info: null,
        },
        78: {
          ...mockDiskDetail,
          descriptor: 'SLOT 077,3FJ2NW8T',
          status: 'OK',
          dev: 'sdarx',
          pool_info: null,
        },
        79: {
          ...mockDiskDetail,
          descriptor: 'SLOT 078,3FJGYY8T',
          status: 'OK',
          dev: 'sdary',
          pool_info: null,
        },
        80: {
          ...mockDiskDetail,
          descriptor: 'SLOT 079,3FJJ1DAT',
          status: 'OK',
          dev: 'sdarz',
          pool_info: null,
        },
        81: {
          ...mockDiskDetail,
          descriptor: 'SLOT 080,3FJJ780T',
          status: 'OK',
          dev: 'sdasa',
          pool_info: null,
        },
        82: {
          ...mockDiskDetail,
          descriptor: 'SLOT 081,3FJKAJ0T',
          status: 'OK',
          dev: 'sdasb',
          pool_info: null,
        },
        83: {
          ...mockDiskDetail,
          descriptor: 'SLOT 082,3FJJ76KT',
          status: 'OK',
          dev: 'sdasc',
          pool_info: null,
        },
        84: {
          ...mockDiskDetail,
          descriptor: 'SLOT 083,3FJKLX1T',
          status: 'OK',
          dev: 'sdasd',
          pool_info: null,
        },
        85: {
          ...mockDiskDetail,
          descriptor: 'SLOT 084,3FJJZZ8T',
          status: 'OK',
          dev: 'sdase',
          pool_info: null,
        },
        86: {
          ...mockDiskDetail,
          descriptor: 'SLOT 085,3FHV6WBT',
          status: 'OK',
          dev: 'sdasf',
          pool_info: null,
        },
        87: {
          ...mockDiskDetail,
          descriptor: 'SLOT 086,3FJG5GET',
          status: 'OK',
          dev: 'sdasg',
          pool_info: null,
        },
        88: {
          ...mockDiskDetail,
          descriptor: 'SLOT 087,3FJG5BPT',
          status: 'OK',
          dev: 'sdash',
          pool_info: null,
        },
        89: {
          ...mockDiskDetail,
          descriptor: 'SLOT 088,3FJGYYET',
          status: 'OK',
          dev: 'sdasi',
          pool_info: null,
        },
        90: {
          ...mockDiskDetail,
          descriptor: 'SLOT 089,3FJJZN9T',
          status: 'OK',
          dev: 'sdasj',
          pool_info: null,
        },
        91: {
          ...mockDiskDetail,
          descriptor: 'SLOT 090,3FJGE2YT',
          status: 'OK',
          dev: 'sdask',
          pool_info: null,
        },
        92: {
          ...mockDiskDetail,
          descriptor: 'SLOT 091,3FJKLX6T',
          status: 'OK',
          dev: 'sdasl',
          pool_info: null,
        },
        93: {
          ...mockDiskDetail,
          descriptor: 'SLOT 092,3FHT3KDT',
          status: 'OK',
          dev: 'sdasm',
          pool_info: null,
        },
        94: {
          ...mockDiskDetail,
          descriptor: 'SLOT 093,3FJJZY6T',
          status: 'OK',
          dev: 'sdasq',
          pool_info: null,
        },
        95: {
          ...mockDiskDetail,
          descriptor: 'SLOT 094,3FJ1UGTT',
          status: 'OK',
          dev: 'sdasn',
          pool_info: null,
        },
        96: {
          ...mockDiskDetail,
          descriptor: 'SLOT 095,3FJJ407T',
          status: 'OK',
          dev: 'sdaso',
          pool_info: null,
        },
        97: {
          ...mockDiskDetail,
          descriptor: 'SLOT 096,3FHMLGXT',
          status: 'OK',
          dev: 'sdasp',
          pool_info: null,
        },
        98: {
          ...mockDiskDetail,
          descriptor: 'SLOT 097,3FJKLY0T',
          status: 'OK',
          dev: 'sdata',
          pool_info: null,
        },
        99: {
          ...mockDiskDetail,
          descriptor: 'SLOT 098,3FJKLXAT',
          status: 'OK',
          dev: 'sdasr',
          pool_info: null,
        },
        100: {
          ...mockDiskDetail,
          descriptor: 'SLOT 099,3FJGYH5T',
          status: 'OK',
          dev: 'sdass',
          pool_info: null,
        },
        101: {
          ...mockDiskDetail,
          descriptor: 'SLOT 100,3FJH3EAT',
          status: 'OK',
          dev: 'sdast',
          pool_info: null,
        },
        102: {
          ...mockDiskDetail,
          descriptor: 'SLOT 101,3FJG5A5T',
          status: 'OK',
          dev: 'sdasu',
          pool_info: null,
        },
      },
      Enclosure: {
        104: {
          ...mockDiskDetail,
          descriptor: 'ENCLOSURE,1ES1846-A3,THCCT03821EA0078,1EB1173-A1,THCCT03721EJ189A',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
      },
      'Power Supply': {
        106: {
          ...mockDiskDetail,
          descriptor: 'POWER SUPPLY A,CSU1800AP-3-10,N86821003EAKZ,,Artesyn,1800W',
          status: 'OK',
          value: 'Hot swap, RQST on',
          value_raw: 16777376,
        },
        107: {
          ...mockDiskDetail,
          descriptor: 'POWER SUPPLY B,CSU1800AP-3-10,N86821009SAKZ,,Artesyn,1800W',
          status: 'OK',
          value: 'Hot swap, RQST on',
          value_raw: 16777376,
        },
      },
      Cooling: {
        109: {
          ...mockDiskDetail,
          descriptor: 'FAN ENCL 1',
          status: 'OK',
          value: '7280 RPM',
          value_raw: 16963748,
        },
        110: {
          ...mockDiskDetail,
          descriptor: 'FAN ENCL 2',
          status: 'OK',
          value: '7280 RPM',
          value_raw: 16963748,
        },
        111: {
          ...mockDiskDetail,
          descriptor: 'FAN ENCL 3',
          status: 'OK',
          value: '7290 RPM',
          value_raw: 16964004,
        },
        112: {
          ...mockDiskDetail,
          descriptor: 'FAN ENCL 4',
          status: 'OK',
          value: '7330 RPM',
          value_raw: 16965028,
        },
        113: {
          ...mockDiskDetail,
          descriptor: 'FAN IOM 1',
          status: 'OK',
          value: '20470 RPM',
          value_raw: 17301415,
        },
        114: {
          ...mockDiskDetail,
          descriptor: 'FAN IOM 2',
          status: 'OK',
          value: '20470 RPM',
          value_raw: 17301415,
        },
        115: {
          ...mockDiskDetail,
          descriptor: 'FAN PSU A',
          status: 'OK',
          value: '20470 RPM',
          value_raw: 17301415,
        },
        116: {
          ...mockDiskDetail,
          descriptor: 'FAN PSU B',
          status: 'OK',
          value: '2720 RPM',
          value_raw: 16847015,
        },
      },
      'Temperature Sensors': {
        118: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 000',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        119: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 001',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        120: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 002',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        121: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 003',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        122: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 004',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        123: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 005',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        124: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 006',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        125: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 007',
          status: 'OK',
          value: '27C',
          value_raw: 16789248,
        },
        126: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 008',
          status: 'OK',
          value: '27C',
          value_raw: 16789248,
        },
        127: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 009',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        128: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 010',
          status: 'OK',
          value: '28C',
          value_raw: 16789504,
        },
        129: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 011',
          status: 'OK',
          value: '27C',
          value_raw: 16789248,
        },
        130: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 012',
          status: 'OK',
          value: '27C',
          value_raw: 16789248,
        },
        131: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 013',
          status: 'OK',
          value: '27C',
          value_raw: 16789248,
        },
        132: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 014',
          status: 'OK',
          value: '33C',
          value_raw: 16790784,
        },
        133: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 015',
          status: 'OK',
          value: '35C',
          value_raw: 16791296,
        },
        134: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 016',
          status: 'OK',
          value: '35C',
          value_raw: 16791296,
        },
        135: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 017',
          status: 'OK',
          value: '35C',
          value_raw: 16791296,
        },
        136: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 018',
          status: 'OK',
          value: '35C',
          value_raw: 16791296,
        },
        137: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 019',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        138: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 020',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        139: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 021',
          status: 'OK',
          value: '33C',
          value_raw: 16790784,
        },
        140: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 022',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        141: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 023',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        142: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 024',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        143: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 025',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        144: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 026',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        145: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 027',
          status: 'OK',
          value: '34C',
          value_raw: 16791040,
        },
        146: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 028',
          status: 'OK',
          value: '37C',
          value_raw: 16791808,
        },
        147: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 029',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        148: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 030',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        149: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 031',
          status: 'OK',
          value: '41C',
          value_raw: 16792832,
        },
        150: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 032',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        151: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 033',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        152: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 034',
          status: 'OK',
          value: '39C',
          value_raw: 16792320,
        },
        153: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 035',
          status: 'OK',
          value: '37C',
          value_raw: 16791808,
        },
        154: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 036',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        155: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 037',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        156: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 038',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        157: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 039',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        158: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 040',
          status: 'OK',
          value: '39C',
          value_raw: 16792320,
        },
        159: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 041',
          status: 'OK',
          value: '38C',
          value_raw: 16792064,
        },
        160: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 042',
          status: 'OK',
          value: '39C',
          value_raw: 16792320,
        },
        161: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 043',
          status: 'OK',
          value: '44C',
          value_raw: 16793600,
        },
        162: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 044',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        163: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 045',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        164: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 046',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        165: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 047',
          status: 'OK',
          value: '42C',
          value_raw: 16793088,
        },
        166: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 048',
          status: 'OK',
          value: '42C',
          value_raw: 16793088,
        },
        167: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 049',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        168: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 050',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        169: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 051',
          status: 'OK',
          value: '44C',
          value_raw: 16793600,
        },
        170: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 052',
          status: 'OK',
          value: '42C',
          value_raw: 16793088,
        },
        171: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 053',
          status: 'OK',
          value: '38C',
          value_raw: 16792064,
        },
        172: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 054',
          status: 'OK',
          value: '41C',
          value_raw: 16792832,
        },
        173: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 055',
          status: 'OK',
          value: '41C',
          value_raw: 16792832,
        },
        174: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 056',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        175: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 057',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        176: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 058',
          status: 'OK',
          value: '39C',
          value_raw: 16792320,
        },
        177: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 059',
          status: 'OK',
          value: '36C',
          value_raw: 16791552,
        },
        178: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 060',
          status: 'OK',
          value: '35C',
          value_raw: 16791296,
        },
        179: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 061',
          status: 'OK',
          value: '37C',
          value_raw: 16791808,
        },
        180: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 062',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        181: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 063',
          status: 'OK',
          value: '41C',
          value_raw: 16792832,
        },
        182: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 064',
          status: 'OK',
          value: '40C',
          value_raw: 16792576,
        },
        183: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 065',
          status: 'OK',
          value: '41C',
          value_raw: 16792832,
        },
        184: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 066',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        185: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 067',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        186: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 068',
          status: 'OK',
          value: '48C',
          value_raw: 16794624,
        },
        187: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 069',
          status: 'OK',
          value: '48C',
          value_raw: 16794624,
        },
        188: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 070',
          status: 'OK',
          value: '46C',
          value_raw: 16794112,
        },
        189: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 071',
          status: 'OK',
          value: '44C',
          value_raw: 16793600,
        },
        190: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 072',
          status: 'OK',
          value: '44C',
          value_raw: 16793600,
        },
        191: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 073',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        192: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 074',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        193: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 075',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        194: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 076',
          status: 'OK',
          value: '46C',
          value_raw: 16794112,
        },
        195: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 077',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        196: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 078',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        197: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 079',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        198: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 080',
          status: 'OK',
          value: '50C',
          value_raw: 16795136,
        },
        199: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 081',
          status: 'OK',
          value: '51C',
          value_raw: 16795392,
        },
        200: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 082',
          status: 'OK',
          value: '50C',
          value_raw: 16795136,
        },
        201: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 083',
          status: 'OK',
          value: '50C',
          value_raw: 16795136,
        },
        202: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 084',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        203: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 085',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        204: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 086',
          status: 'OK',
          value: '50C',
          value_raw: 16795136,
        },
        205: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 087',
          status: 'OK',
          value: '50C',
          value_raw: 16795136,
        },
        206: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 088',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        207: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 089',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        208: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 090',
          status: 'OK',
          value: '43C',
          value_raw: 16793344,
        },
        209: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 091',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        210: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 092',
          status: 'OK',
          value: '48C',
          value_raw: 16794624,
        },
        211: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 093',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        212: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 094',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        213: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 095',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        214: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 096',
          status: 'OK',
          value: '46C',
          value_raw: 16794112,
        },
        215: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 097',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        216: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 098',
          status: 'OK',
          value: '48C',
          value_raw: 16794624,
        },
        217: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 099',
          status: 'OK',
          value: '48C',
          value_raw: 16794624,
        },
        218: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 100',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        219: {
          ...mockDiskDetail,
          descriptor: 'TEMP SLOT 101',
          status: 'OK',
          value: '44C',
          value_raw: 16793600,
        },
        220: {
          ...mockDiskDetail,
          descriptor: 'TEMP IOM A',
          status: 'OK',
          value: '45C',
          value_raw: 16793856,
        },
        221: {
          ...mockDiskDetail,
          descriptor: 'TEMP IOM B',
          status: 'OK',
          value: '49C',
          value_raw: 16794880,
        },
        222: {
          ...mockDiskDetail,
          descriptor: 'TEMP BB 60 1',
          status: 'OK',
          value: '30C',
          value_raw: 16790016,
        },
        223: {
          ...mockDiskDetail,
          descriptor: 'TEMP BB 60 2',
          status: 'OK',
          value: '30C',
          value_raw: 16790016,
        },
        224: {
          ...mockDiskDetail,
          descriptor: 'TEMP BB 42 1',
          status: 'OK',
          value: '16C',
          value_raw: 16786432,
        },
        225: {
          ...mockDiskDetail,
          descriptor: 'TEMP BB 42 2',
          status: 'OK',
          value: '17C',
          value_raw: 16786688,
        },
        226: {
          ...mockDiskDetail,
          descriptor: 'TEMP PRI A DIE',
          status: 'OK',
          value: '54C',
          value_raw: 16796160,
        },
        227: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC1 A DIE',
          status: 'OK',
          value: '69C',
          value_raw: 16800000,
        },
        228: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC2 A DIE',
          status: 'OK',
          value: '58C',
          value_raw: 16797184,
        },
        229: {
          ...mockDiskDetail,
          descriptor: 'TEMP PRI A MEM',
          status: 'OK',
          value: '43C',
          value_raw: 16793344,
        },
        230: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC1 A MEM',
          status: 'OK',
          value: '42C',
          value_raw: 16793088,
        },
        231: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC2 A MEM',
          status: 'OK',
          value: '37C',
          value_raw: 16791808,
        },
        232: {
          ...mockDiskDetail,
          descriptor: 'TEMP PRI B DIE',
          status: 'OK',
          value: '56C',
          value_raw: 16796672,
        },
        233: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC1 B DIE',
          status: 'OK',
          value: '76C',
          value_raw: 16801792,
        },
        234: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC2 B DIE',
          status: 'OK',
          value: '62C',
          value_raw: 16798208,
        },
        235: {
          ...mockDiskDetail,
          descriptor: 'TEMP PRI B MEM',
          status: 'OK',
          value: '46C',
          value_raw: 16794112,
        },
        236: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC1 B MEM',
          status: 'OK',
          value: '47C',
          value_raw: 16794368,
        },
        237: {
          ...mockDiskDetail,
          descriptor: 'TEMP SEC2 B MEM',
          status: 'OK',
          value: '37C',
          value_raw: 16791808,
        },
        238: {
          ...mockDiskDetail,
          descriptor: 'TEMP IOM A 5V',
          status: 'OK',
          value: '54C',
          value_raw: 16796160,
        },
        239: {
          ...mockDiskDetail,
          descriptor: 'TEMP IOM B 5V',
          status: 'OK',
          value: '55C',
          value_raw: 16796416,
        },
        240: {
          ...mockDiskDetail,
          descriptor: 'TEMP PSU A AMB',
          status: 'OK',
          value: '39C',
          value_raw: 16792320,
        },
        241: {
          ...mockDiskDetail,
          descriptor: 'TEMP PSU A HOT',
          status: 'OK',
          value: '48C',
          value_raw: 16794624,
        },
        242: {
          ...mockDiskDetail,
          descriptor: 'TEMP PSU A PRI',
          status: 'OK',
          value: '43C',
          value_raw: 16793344,
        },
        243: {
          ...mockDiskDetail,
          descriptor: 'TEMP PSU B AMB',
          status: 'OK',
          value: '31C',
          value_raw: 16790272,
        },
        244: {
          ...mockDiskDetail,
          descriptor: 'TEMP PSU B HOT',
          status: 'OK',
          value: '69C',
          value_raw: 16800000,
        },
        245: {
          ...mockDiskDetail,
          descriptor: 'TEMP PSU B PRI',
          status: 'OK',
          value: '67C',
          value_raw: 16799488,
        },
      },
      'Enclosure Services Controller Electronics': {
        247: {
          ...mockDiskDetail,
          descriptor: 'ESCE IOMA,1EA0484-C1          ,THCCT03821EG010D    ,5000CCAB051145BC,,00:0C:CA:07:44:98,3.1.11',
          status: 'OK',
          value: null,
          value_raw: 17826176,
        },
        248: {
          ...mockDiskDetail,
          descriptor: 'ESCE IOMB,1EA0484-C1          ,THCCT03821EG010E    ,5000CCAB051145FC,,00:0C:CA:07:44:62,3.1.11',
          status: 'OK',
          value: null,
          value_raw: 17825920,
        },
      },
      'SAS Expander': {
        250: {
          ...mockDiskDetail,
          descriptor: 'EXP IOMA 0,3010-007,5000CCAB051145BD',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
        251: {
          ...mockDiskDetail,
          descriptor: 'EXP IOMA 1,3010-007,5000CCAB051145BF',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
        252: {
          ...mockDiskDetail,
          descriptor: 'EXP IOMA 2,3010-007,5000CCAB051145FF',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
        253: {
          ...mockDiskDetail,
          descriptor: 'EXP IOMB 0,3010-007,5000CCAB051145FD',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
        254: {
          ...mockDiskDetail,
          descriptor: 'EXP IOMB 1,3010-007,5000CCAB051145F9',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
        255: {
          ...mockDiskDetail,
          descriptor: 'EXP IOMB 2,3010-007,5000CCAB051145FB',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
      },
      'SAS Connector': {
        257: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 00',
          status: 'OK',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 17170304,
        },
        258: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 01',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        259: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 02',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        260: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 03',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        261: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 04',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        262: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 05',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        263: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 06',
          status: 'Critical',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 33947520,
        },
        264: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 07',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        265: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 08',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        266: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 09',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        267: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 10',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
        268: {
          ...mockDiskDetail,
          descriptor: 'CONN HOST 11',
          status: 'Not installed',
          value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
          value_raw: 84279040,
        },
      },
      'Voltage Sensor': {
        270: {
          ...mockDiskDetail,
          descriptor: 'VOLT PSU A AC',
          status: 'OK',
          value: '199.0V',
          value_raw: 16797116,
        },
        271: {
          ...mockDiskDetail,
          descriptor: 'VOLT PSU A 12V',
          status: 'OK',
          value: '12.29V',
          value_raw: 16778445,
        },
        272: {
          ...mockDiskDetail,
          descriptor: 'VOLT PSU B AC',
          status: 'OK',
          value: '200.0V',
          value_raw: 16797216,
        },
        273: {
          ...mockDiskDetail,
          descriptor: 'VOLT PSU B 12V',
          status: 'OK',
          value: '12.26V',
          value_raw: 16778442,
        },
        274: {
          ...mockDiskDetail,
          descriptor: 'VOLT IOM A 5V',
          status: 'OK',
          value: '4.99V',
          value_raw: 16777715,
        },
        275: {
          ...mockDiskDetail,
          descriptor: 'VOLT IOM A 12V',
          status: 'OK',
          value: '12.0V',
          value_raw: 16778416,
        },
        276: {
          ...mockDiskDetail,
          descriptor: 'VOLT IOM B 5V',
          status: 'OK',
          value: '4.99V',
          value_raw: 16777715,
        },
        277: {
          ...mockDiskDetail,
          descriptor: 'VOLT IOM B 12V',
          status: 'OK',
          value: '12.0V',
          value_raw: 16778416,
        },
      },
      'Current Sensor': {
        279: {
          ...mockDiskDetail,
          descriptor: 'CURR PSU A IN',
          status: 'OK',
          value: '2.72A',
          value_raw: 16777488,
        },
        280: {
          ...mockDiskDetail,
          descriptor: 'CURR PSU A OUT',
          status: 'OK',
          value: '39.88A',
          value_raw: 16781204,
        },
        281: {
          ...mockDiskDetail,
          descriptor: 'CURR PSU B IN',
          status: 'OK',
          value: '2.6A',
          value_raw: 16777476,
        },
        282: {
          ...mockDiskDetail,
          descriptor: 'CURR PSU B OUT',
          status: 'OK',
          value: '39.69A',
          value_raw: 16781185,
        },
        283: {
          ...mockDiskDetail,
          descriptor: 'CURR IOM A 12V',
          status: 'OK',
          value: '20.2A',
          value_raw: 16779236,
        },
        284: {
          ...mockDiskDetail,
          descriptor: 'CURR IOM A 5V',
          status: 'OK',
          value: '37.25A',
          value_raw: 16780941,
        },
        285: {
          ...mockDiskDetail,
          descriptor: 'CURR IOM B 12V',
          status: 'OK',
          value: '18.48A',
          value_raw: 16779064,
        },
        286: {
          ...mockDiskDetail,
          descriptor: 'CURR IOM B 5V',
          status: 'OK',
          value: '31.5A',
          value_raw: 16780366,
        },
      },
      'Door Lock': {
        288: {
          ...mockDiskDetail,
          descriptor: 'ENCLOSURE COVER',
          status: 'OK',
          value: null,
          value_raw: 16777216,
        },
      },
    },
    label: 'HGST H4102-J 3010',
  } as EnclosureUi;

  constructor(number: number) {
    super(number);
    this.enclosureNumber = number;
    this.enclosureInit();
  }
}
