import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { UntilDestroy, untilDestroyed } from '@ngneat/until-destroy';
import { TranslateService } from '@ngx-translate/core';
import { UUID } from 'angular2-uuid';
import { environment } from 'environments/environment';
import {
  merge, Observable, of, Subject, throwError,
} from 'rxjs';
import {
  filter, map, share, switchMap, take, takeUntil, takeWhile, tap,
} from 'rxjs/operators';
import { MockEnclosureUtils } from 'app/core/testing/utils/mock-enclosure.utils';
import { IncomingApiMessageType } from 'app/enums/api-message-type.enum';
import { JobState } from 'app/enums/job-state.enum';
import { ResponseErrorType } from 'app/enums/response-error-type.enum';
import { WebsocketErrorName } from 'app/enums/websocket-error-name.enum';
import { ApiCallDirectory, ApiCallMethod } from 'app/interfaces/api/api-call-directory.interface';
import { ApiEventDirectory } from 'app/interfaces/api/api-event-directory.interface';
import { ApiJobDirectory, ApiJobMethod } from 'app/interfaces/api/api-job-directory.interface';
import { ApiEvent, IncomingWebsocketMessage, ResultMessage } from 'app/interfaces/api-message.interface';
import { Job } from 'app/interfaces/job.interface';
import { WebsocketError } from 'app/interfaces/websocket-error.interface';
import { WebsocketConnectionService } from 'app/services/websocket-connection.service';

@UntilDestroy()
@Injectable({
  providedIn: 'root',
})
export class WebSocketService {
  private readonly eventSubscriptions = new Map<string, { obs$: Observable<unknown>; takeUntil$: Subject<void> }>();
  mockUtils: MockEnclosureUtils;

  constructor(
    protected router: Router,
    protected wsManager: WebsocketConnectionService,
    protected translate: TranslateService,
  ) {
    if (environment.mockConfig && !environment?.production) this.mockUtils = new MockEnclosureUtils();
    this.wsManager.isConnected$?.pipe(untilDestroyed(this)).subscribe((isConnected) => {
      if (!isConnected) {
        this.clearSubscriptions();
      }
    });
  }

  private get ws$(): Observable<unknown> {
    return this.wsManager.websocket$;
  }

  call<M extends ApiCallMethod>(method: M, params?: ApiCallDirectory[M]['params']): Observable<ApiCallDirectory[M]['response']> {
    if (method === 'enclosure.query') {
      return of([
        {
          id: '5b0bd6d1a305eeff',
          bsg: 'bsg/17:0:2:0',
          name: 'iX 4024Sp e001',
          model: 'M Series',
          controller: true,
          elements: [
            {
              name: 'Array Device Slot',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
                'Device',
              ],
              elements: [
                {
                  slot: 1,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                    Device: 'sda',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                    Device: 'sde',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 5,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 6,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 7,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 8,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 9,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 10,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 11,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 12,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 13,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 14,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 15,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 16,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 17,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 18,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 19,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 20,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 21,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 22,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 23,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 24,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
              ],
              has_slot_status: true,
            },
            {
              name: 'Enclosure',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                  },
                  name: 'Enclosure',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'Temperature Sensor',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '33C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '33C',
                  value_raw: '0x1003500',
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '19C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '19C',
                  value_raw: '0x1002700',
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '19C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '19C',
                  value_raw: '0x1002700',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'Voltage Sensor',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '12.18V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '12.18V',
                  value_raw: '0x10004c2',
                },
              ],
              has_slot_status: false,
            },
          ],
          number: 0,
          label: 'iX 4024Sp e001',
        },
        {
          id: '500e0eca095179ff',
          bsg: 'bsg/19:0:3:0',
          name: 'CELESTIC R0904-F0001-01 0422',
          model: 'ES60',
          controller: false,
          elements: [
            {
              name: 'Array Device Slot',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
                'Device',
              ],
              elements: [
                {
                  slot: 1,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                    Device: 'sdb',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                    Device: 'sdc',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                    Device: 'sdd',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 5,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 6,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 7,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 8,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 9,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 10,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 11,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 12,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 13,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 14,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 15,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 16,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 17,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 18,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 19,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 20,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 21,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 22,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 23,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 24,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 25,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 26,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 27,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 28,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 29,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 30,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 31,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 32,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 33,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 34,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 35,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 36,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 37,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 38,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 39,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 40,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 41,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 42,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 43,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 44,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 45,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 46,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 47,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 48,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 49,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 50,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 51,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 52,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 53,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 54,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 55,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 56,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 57,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 58,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 59,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
                {
                  slot: 60,
                  data: {
                    Descriptor: '',
                    Status: 'Not installed',
                    Value: 'None',
                    Device: '',
                  },
                  name: 'Array Device Slot',
                  descriptor: '',
                  status: 'Not installed',
                  value: 'None',
                  value_raw: '0x5000000',
                  fault: false,
                  identify: false,
                },
              ],
              has_slot_status: true,
            },
            {
              name: 'Cooling',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '5750 RPM',
                  },
                  name: 'Cooling',
                  descriptor: '',
                  status: 'OK',
                  value: '5750 RPM',
                  value_raw: '0x1023f01',
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '5700 RPM',
                  },
                  name: 'Cooling',
                  descriptor: '',
                  status: 'OK',
                  value: '5700 RPM',
                  value_raw: '0x1023a01',
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '5800 RPM',
                  },
                  name: 'Cooling',
                  descriptor: '',
                  status: 'OK',
                  value: '5800 RPM',
                  value_raw: '0x1024401',
                },
                {
                  slot: 5,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '5800 RPM',
                  },
                  name: 'Cooling',
                  descriptor: '',
                  status: 'OK',
                  value: '5800 RPM',
                  value_raw: '0x1024401',
                },
                {
                  slot: 6,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '5800 RPM',
                  },
                  name: 'Cooling',
                  descriptor: '',
                  status: 'OK',
                  value: '5800 RPM',
                  value_raw: '0x1024401',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'Enclosure Services Controller Electronics',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 384,
                  },
                  name: 'Enclosure Services Controller Electronics',
                  descriptor: '',
                  status: 'OK',
                  value: 384,
                  value_raw: '0x1000180',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'Power Supply',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                  },
                  name: 'Power Supply',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000020',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'SAS Connector',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
                  },
                  name: 'SAS Connector',
                  descriptor: '',
                  status: 'OK',
                  value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
                  value_raw: '0x105ff00',
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
                  },
                  name: 'SAS Connector',
                  descriptor: '',
                  status: 'OK',
                  value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
                  value_raw: '0x105ff00',
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
                  },
                  name: 'SAS Connector',
                  descriptor: '',
                  status: 'OK',
                  value: 'Mini SAS HD 4x receptacle (SFF-8644) [max 4 phys]',
                  value_raw: '0x105ff00',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'SAS Expander',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: 'None',
                  },
                  name: 'SAS Expander',
                  descriptor: '',
                  status: 'OK',
                  value: 'None',
                  value_raw: '0x1000000',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'Temperature Sensor',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '20C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '20C',
                  value_raw: '0x1002800',
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '24C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '24C',
                  value_raw: '0x1002c00',
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '29C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '29C',
                  value_raw: '0x1003100',
                },
                {
                  slot: 5,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '22C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '22C',
                  value_raw: '0x1002a00',
                },
                {
                  slot: 6,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '22C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '22C',
                  value_raw: '0x1002a00',
                },
                {
                  slot: 7,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '22C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '22C',
                  value_raw: '0x1002a00',
                },
                {
                  slot: 8,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '29C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '29C',
                  value_raw: '0x1003100',
                },
                {
                  slot: 9,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '21C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '21C',
                  value_raw: '0x1002900',
                },
                {
                  slot: 10,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '18C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '18C',
                  value_raw: '0x1002600',
                },
                {
                  slot: 11,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '31C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '31C',
                  value_raw: '0x1003300',
                },
                {
                  slot: 12,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '20C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '20C',
                  value_raw: '0x1002800',
                },
                {
                  slot: 13,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '22C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '22C',
                  value_raw: '0x1002a00',
                },
                {
                  slot: 14,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '30C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '30C',
                  value_raw: '0x1003200',
                },
                {
                  slot: 15,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '21C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '21C',
                  value_raw: '0x1002900',
                },
                {
                  slot: 16,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '22C',
                  },
                  name: 'Temperature Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '22C',
                  value_raw: '0x1002a00',
                },
              ],
              has_slot_status: false,
            },
            {
              name: 'Voltage Sensor',
              descriptor: '',
              header: [
                'Descriptor',
                'Status',
                'Value',
              ],
              elements: [
                {
                  slot: 2,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '1.0V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '1.0V',
                  value_raw: '0x1000064',
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '1.8V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '1.8V',
                  value_raw: '0x10000b4',
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '3.31V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '3.31V',
                  value_raw: '0x100014b',
                },
                {
                  slot: 5,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '0.93V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '0.93V',
                  value_raw: '0x100005d',
                },
                {
                  slot: 6,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '1.0V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '1.0V',
                  value_raw: '0x1000064',
                },
                {
                  slot: 7,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '1.81V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '1.81V',
                  value_raw: '0x10000b5',
                },
                {
                  slot: 8,
                  data: {
                    Descriptor: '',
                    Status: 'OK',
                    Value: '3.34V',
                  },
                  name: 'Voltage Sensor',
                  descriptor: '',
                  status: 'OK',
                  value: '3.34V',
                  value_raw: '0x100014e',
                },
              ],
              has_slot_status: false,
            },
          ],
          number: 1,
          label: 'CELESTIC R0904-F0001-01 0422',
        },
        {
          id: 'm60_plx_enclosure',
          bsg: null,
          name: 'Rear NVME U.2 Hotswap Bays',
          model: 'M60 Series',
          controller: true,
          elements: [
            {
              name: 'Array Device Slot',
              descriptor: 'Drive Slots',
              header: [
                'Descriptor',
                'Status',
                'Value',
                'Device',
              ],
              elements: [
                {
                  slot: 1,
                  data: {
                    Descriptor: 'Disk #1',
                    Status: 'Not Installed',
                    Value: 'None',
                    Device: null,
                  },
                  name: 'Array Device Slot',
                  descriptor: 'Disk #1',
                  status: 'Not Installed',
                  value: 'None',
                  value_raw: '0x05000000',
                },
                {
                  slot: 2,
                  data: {
                    Descriptor: 'Disk #2',
                    Status: 'Not Installed',
                    Value: 'None',
                    Device: null,
                  },
                  name: 'Array Device Slot',
                  descriptor: 'Disk #2',
                  status: 'Not Installed',
                  value: 'None',
                  value_raw: '0x05000000',
                },
                {
                  slot: 3,
                  data: {
                    Descriptor: 'Disk #3',
                    Status: 'Not Installed',
                    Value: 'None',
                    Device: null,
                  },
                  name: 'Array Device Slot',
                  descriptor: 'Disk #3',
                  status: 'Not Installed',
                  value: 'None',
                  value_raw: '0x05000000',
                },
                {
                  slot: 4,
                  data: {
                    Descriptor: 'Disk #4',
                    Status: 'Not Installed',
                    Value: 'None',
                    Device: null,
                  },
                  name: 'Array Device Slot',
                  descriptor: 'Disk #4',
                  status: 'Not Installed',
                  value: 'None',
                  value_raw: '0x05000000',
                },
              ],
              has_slot_status: false,
            },
          ],
          number: 2,
          label: 'Rear NVME U.2 Hotswap Bays',
        },
      ]);
    }
    if (method === 'disk.query') {
      return of([
        {
          identifier: '{serial_lunid}NHGPZ5MY_5000cca24327f45c',
          name: 'sdd',
          subsystem: 'scsi',
          number: 2096,
          serial: 'NHGPZ5MY',
          lunid: '5000cca24327f45c',
          size: 4000787030016,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: 'HUS726040AL4210',
          rotationrate: 7200,
          type: 'HDD',
          zfs_guid: '6946050239345913114',
          bus: 'SCSI',
          devname: 'sdd',
          enclosure: {
            number: 0,
            slot: 1,
          },
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial_lunid}NHG85B8J_5000cca2430edc68',
          name: 'sde',
          subsystem: 'scsi',
          number: 2112,
          serial: 'NHG85B8J',
          lunid: '5000cca2430edc68',
          size: 4000787030016,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: 'HUS726040AL5210',
          rotationrate: 7200,
          type: 'HDD',
          zfs_guid: '4072536647347656601',
          bus: 'SCSI',
          devname: 'sde',
          enclosure: {
            number: 0,
            slot: 2,
          },
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial_lunid}2GG3DJ7D_5000cca2be063080',
          name: 'sda',
          subsystem: 'scsi',
          number: 2048,
          serial: '2GG3DJ7D',
          lunid: '5000cca2be063080',
          size: 22000969973760,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: 'WUH722222AL5201',
          rotationrate: 7200,
          type: 'HDD',
          zfs_guid: '1193385697121509581',
          bus: 'SCSI',
          devname: 'sda',
          enclosure: {
            number: 1,
            slot: 1,
          },
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial_lunid}2GG3DB8D_5000cca2be062e18',
          name: 'sdb',
          subsystem: 'scsi',
          number: 2064,
          serial: '2GG3DB8D',
          lunid: '5000cca2be062e18',
          size: 22000969973760,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: 'WUH722222AL5201',
          rotationrate: 7200,
          type: 'HDD',
          zfs_guid: null,
          bus: 'SCSI',
          devname: 'sdb',
          enclosure: {
            number: 1,
            slot: 2,
          },
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial_lunid}2GG3734D_5000cca2be05df14',
          name: 'sdc',
          subsystem: 'scsi',
          number: 2080,
          serial: '2GG3734D',
          lunid: '5000cca2be05df14',
          size: 22000969973760,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: 'WUH722222AL5201',
          rotationrate: 7200,
          type: 'HDD',
          zfs_guid: '13745555504549908384',
          bus: 'SCSI',
          devname: 'sdc',
          enclosure: {
            number: 1,
            slot: 3,
          },
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial_lunid}2017EY450205_e8238fa6bf530001001b444a442358dc',
          name: 'nvme0n1',
          subsystem: 'nvme',
          number: 66304,
          serial: '2017EY450205',
          lunid: 'e8238fa6bf530001001b444a442358dc',
          size: 250059350016,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: 'WDC WDS250G2B0C-00PXH0',
          rotationrate: null,
          type: 'SSD',
          zfs_guid: null,
          bus: 'UNKNOWN',
          devname: 'nvme0n1',
          enclosure: null,
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial}FB2E87C4912FFD6A',
          name: 'pmem1',
          subsystem: 'nd',
          number: 66310,
          serial: 'FB2E87C4912FFD6A',
          lunid: null,
          size: 34359734272,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: null,
          rotationrate: null,
          type: 'SSD',
          zfs_guid: null,
          bus: 'UNKNOWN',
          devname: 'pmem1',
          enclosure: null,
          supports_smart: null,
          pool: null,
        },
        {
          identifier: '{serial}F00147E4A8C54CA6',
          name: 'pmem0',
          subsystem: 'nd',
          number: 66309,
          serial: 'F00147E4A8C54CA6',
          lunid: null,
          size: 34359734272,
          description: '',
          transfermode: 'Auto',
          hddstandby: 'ALWAYS ON',
          advpowermgmt: 'DISABLED',
          togglesmart: true,
          smartoptions: '',
          expiretime: null,
          critical: null,
          difference: null,
          informational: null,
          model: null,
          rotationrate: null,
          type: 'SSD',
          zfs_guid: null,
          bus: 'UNKNOWN',
          devname: 'pmem0',
          enclosure: null,
          supports_smart: null,
          pool: null,
        },
      ]);
    }
    if (method === 'pool.query') {
      return of([
        {
          id: 1,
          name: 'sanity',
          guid: '10949025419294039227',
          path: '/mnt/sanity',
          status: 'ONLINE',
          scan: {
            function: 'SCRUB',
            state: 'FINISHED',
            start_time: {
              $date: 1702195200000,
            },
            end_time: {
              $date: 1702195220000,
            },
            percentage: 99.67586398124695,
            bytes_to_process: 1548013568,
            bytes_processed: 1553047552,
            bytes_issued: 1548013568,
            pause: null,
            errors: 0,
            total_secs_left: null,
          },
          topology: {
            data: [
              {
                name: 'mirror-0',
                type: 'MIRROR',
                path: null,
                guid: '7324637794100630703',
                status: 'ONLINE',
                stats: {
                  timestamp: 60798280608954,
                  read_errors: 0,
                  write_errors: 0,
                  checksum_errors: 0,
                  ops: [
                    0,
                    1839,
                    45075,
                    0,
                    0,
                    0,
                    0,
                  ],
                  bytes: [
                    0,
                    47714304,
                    589570048,
                    0,
                    0,
                    0,
                    0,
                  ],
                  size: 3985729650688,
                  allocated: 1998385152,
                  fragmentation: 0,
                  self_healed: 0,
                  configured_ashift: 12,
                  logical_ashift: 12,
                  physical_ashift: 12,
                },
                children: [
                  {
                    name: '6ca539d7-7999-11ee-9431-3cecef0c1cee',
                    type: 'DISK',
                    path: '/dev/disk/by-partuuid/6ca539d7-7999-11ee-9431-3cecef0c1cee',
                    guid: '6946050239345913114',
                    status: 'ONLINE',
                    stats: {
                      timestamp: 60798280785261,
                      read_errors: 0,
                      write_errors: 0,
                      checksum_errors: 0,
                      ops: [
                        0,
                        1059,
                        22543,
                        0,
                        0,
                        0,
                        0,
                      ],
                      bytes: [
                        0,
                        24563712,
                        294785024,
                        0,
                        0,
                        0,
                        0,
                      ],
                      size: 0,
                      allocated: 0,
                      fragmentation: 0,
                      self_healed: 0,
                      configured_ashift: 12,
                      logical_ashift: 12,
                      physical_ashift: 12,
                    },
                    children: [],
                    device: 'sda1',
                    disk: 'sda',
                    unavail_disk: null,
                  },
                  {
                    name: '6ca805da-7999-11ee-9431-3cecef0c1cee',
                    type: 'DISK',
                    path: '/dev/disk/by-partuuid/6ca805da-7999-11ee-9431-3cecef0c1cee',
                    guid: '4072536647347656601',
                    status: 'ONLINE',
                    stats: {
                      timestamp: 60798280892341,
                      read_errors: 0,
                      write_errors: 0,
                      checksum_errors: 0,
                      ops: [
                        0,
                        780,
                        22532,
                        0,
                        0,
                        0,
                        0,
                      ],
                      bytes: [
                        0,
                        23150592,
                        294785024,
                        0,
                        0,
                        0,
                        0,
                      ],
                      size: 0,
                      allocated: 0,
                      fragmentation: 0,
                      self_healed: 0,
                      configured_ashift: 12,
                      logical_ashift: 9,
                      physical_ashift: 12,
                    },
                    children: [],
                    device: 'sde1',
                    disk: 'sde',
                    unavail_disk: null,
                  },
                ],
                unavail_disk: null,
              },
            ],
            log: [],
            cache: [],
            spare: [],
            special: [],
            dedup: [],
          },
          healthy: true,
          warning: true,
          status_code: 'FEAT_DISABLED',
          status_detail: 'Some supported features are not enabled on the pool. The pool can still be used, but some features are unavailable.',
          size: 3985729650688,
          allocated: 1998385152,
          free: 3983731265536,
          freeing: 0,
          fragmentation: '0',
          size_str: '3985729650688',
          allocated_str: '1998385152',
          free_str: '3983731265536',
          freeing_str: '0',
          autotrim: {
            value: 'off',
            rawvalue: 'off',
            parsed: 'off',
            source: 'DEFAULT',
          },
        },
      ]);
    }

    return this.callMethod(method, params);
  }

  /**
   * Use `job` when you care about job progress or result.
   */
  startJob<M extends ApiJobMethod>(method: M, params?: ApiJobDirectory[M]['params']): Observable<number> {
    return this.callMethod(method, params);
  }

  /**
   * In your subscription, next will be next job update, complete will be when the job is complete.
   */
  job<M extends ApiJobMethod>(
    method: M,
    params?: ApiJobDirectory[M]['params'],
  ): Observable<Job<ApiJobDirectory[M]['response']>> {
    return this.callMethod(method, params).pipe(
      switchMap((jobId: number) => {
        return merge(
          this.subscribeToJobUpdates(jobId),
          // Get job status here for jobs that complete too fast.
          this.call('core.get_jobs', [[['id', '=', jobId]]]).pipe(map((jobs) => jobs[0])),
        )
          .pipe(
            takeWhile((job) => job.state !== JobState.Success, true),
            switchMap((job) => {
              if (job.state === JobState.Failed) {
                return throwError(() => job);
              }
              return of(job);
            }),
          );
      }),
    ) as Observable<Job<ApiJobDirectory[M]['response']>>;
  }

  subscribe<K extends keyof ApiEventDirectory>(name: K): Observable<ApiEvent<ApiEventDirectory[K]['response']>> {
    const oldObservable$ = this.eventSubscriptions.get(name)?.obs$;
    if (oldObservable$) {
      return oldObservable$ as Observable<ApiEvent<ApiEventDirectory[K]['response']>>;
    }

    const takeUntil$ = new Subject<void>();
    const subObs$ = this.wsManager.buildSubscriber(name).pipe(
      switchMap((apiEvent: unknown) => {
        const erroredEvent = apiEvent as { error: unknown };
        if (erroredEvent.error) {
          console.error('Error: ', erroredEvent.error);
          return throwError(() => erroredEvent.error);
        }
        return of(apiEvent);
      }),
      share(),
      takeUntil(takeUntil$),
    );
    this.eventSubscriptions.set(name, { obs$: subObs$, takeUntil$ });
    return subObs$ as Observable<ApiEvent<ApiEventDirectory[K]['response']>>;
  }

  subscribeToLogs(name: string): Observable<ApiEvent<{ data: string }>> {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return this.subscribe(name as any) as unknown as Observable<ApiEvent<{ data: string }>>;
  }

  clearSubscriptions(): void {
    this.eventSubscriptions.forEach(
      ({ takeUntil$ }: { takeUntil$: Subject<void> }) => {
        takeUntil$.next();
      },
    );
    this.eventSubscriptions.clear();
  }

  private callMethod<M extends ApiCallMethod>(method: M, params?: ApiCallDirectory[M]['params']): Observable<ApiCallDirectory[M]['response']>;
  private callMethod<M extends ApiJobMethod>(method: M, params?: ApiJobDirectory[M]['params']): Observable<number>;
  private callMethod<M extends ApiCallMethod | ApiJobMethod>(method: M, params?: unknown): Observable<unknown> {
    const uuid = UUID.UUID();
    return of(uuid).pipe(
      tap(() => {
        this.wsManager.send({
          id: uuid, msg: IncomingApiMessageType.Method, method, params,
        });
      }),
      switchMap(() => this.ws$),
      filter((data: IncomingWebsocketMessage) => data.msg === IncomingApiMessageType.Result && data.id === uuid),
      switchMap((data: IncomingWebsocketMessage) => {
        if ('error' in data && data.error) {
          this.printError(data.error, { method, params });
          const error = this.enhanceError(data.error, { method });
          return throwError(() => error);
        }

        if (
          this.mockUtils
          && environment.mockConfig?.enabled
          && this.mockUtils?.canMock
          && data.msg === IncomingApiMessageType.Result
        ) {
          const mockResultMessage: ResultMessage = this.mockUtils.overrideMessage(data, method);
          return of(mockResultMessage);
        }

        return of(data);
      }),

      map((data: ResultMessage) => data.result),
      take(1),
    );
  }

  private subscribeToJobUpdates(jobId: number): Observable<Job> {
    return this.subscribe('core.get_jobs').pipe(
      filter((apiEvent) => apiEvent.id === jobId),
      map((apiEvent) => apiEvent.fields),
    );
  }

  private printError(error: WebsocketError, context: { method: string; params: unknown }): void {
    if (error.errname === WebsocketErrorName.NoAccess) {
      console.error(`Access denied to ${context.method} with ${context.params ? JSON.stringify(context.params) : 'no params'}`);
      return;
    }

    // Do not log validation errors.
    if (error.type === ResponseErrorType.Validation) {
      return;
    }

    console.error('Error: ', error);
  }

  private enhanceError(error: WebsocketError, context: { method: string }): WebsocketError {
    if (error.errname === WebsocketErrorName.NoAccess) {
      return {
        ...error,
        reason: this.translate.instant('Access denied to {method}', { method: context.method }),
      };
    }

    return error;
  }
}
