name: 'Prepare: Checkout and Install'
description: 'Prepares the repo for a job by checking out and installing dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - name: Install packages
      shell: bash
      run: yarn install --frozen-lockfile
