import { marker as T } from '@biesbjerg/ngx-translate-extract-marker';

export enum AuditService {
  Smb = 'SMB',
  Middleware = 'MIDDLEWARE',
  Sudo = 'SUDO',
  System = 'SYSTEM',
}

export enum AuditEvent {
  Connect = 'CONNECT',
  Disconnect = 'DISCONNECT',
  Create = 'CREATE',
  Close = 'CLOSE',
  Read = 'READ',
  Write = 'WRITE',
  OffloadRead = 'OFFLOAD_READ',
  OffloadWrite = 'OFFLOAD_WRITE',
  SetAcl = 'SET_ACL',
  Rename = 'RENAME',
  Unlink = 'UNLINK',
  SetAttr = 'SET_ATTR',
  SetQuota = 'SET_QUOTA',
  Authentication = 'AUTHENTICATION',
  MethodCall = 'METHOD_CALL',
  Accept = 'ACCEPT',
  Generic = 'GENERIC',
  Reject = 'REJECT',
  Reboot = 'REBOOT',
  Logout = 'LOGOUT',
  Login = 'LOGIN',
  Credential = 'CREDENTIAL',
  Escalation = 'ESCALATION',
  Privileged = 'privileged',
  Export = 'export',
  Identity = 'identity',
  TimeChange = 'time-change',
  ModuleLoad = 'module-load',
  Service = 'service',
  TtyRecord = 'tty_record',
}

export const auditServiceLabels = new Map<AuditService, string>([
  [AuditService.Smb, T('SMB')],
  [AuditService.Middleware, T('Middleware')],
  [AuditService.Sudo, T('Sudo')],
  [AuditService.System, T('System')],
]);

export const auditEventLabels = new Map<AuditEvent, string>([
  [AuditEvent.Connect, T('Connect')],
  [AuditEvent.Disconnect, T('Disconnect')],
  [AuditEvent.Create, T('Create')],
  [AuditEvent.Close, T('Close')],
  [AuditEvent.Read, T('Read')],
  [AuditEvent.Write, T('Write')],
  [AuditEvent.OffloadRead, T('Offload Read')],
  [AuditEvent.OffloadWrite, T('Offload Write')],
  [AuditEvent.SetAcl, T('Set ACL')],
  [AuditEvent.Rename, T('Rename')],
  [AuditEvent.Unlink, T('Unlink')],
  [AuditEvent.SetAttr, T('Set Attribute')],
  [AuditEvent.SetQuota, T('Set Quota')],
  [AuditEvent.Authentication, T('Authentication')],
  [AuditEvent.MethodCall, T('Method Call')],
  [AuditEvent.Accept, T('Accept')],
  [AuditEvent.Reject, T('Reject')],
  [AuditEvent.Reboot, T('Reboot')],
  [AuditEvent.Logout, T('Logout')],
  [AuditEvent.Login, T('Login')],
  [AuditEvent.Generic, T('Generic')],
  [AuditEvent.Credential, T('Credential')],
  [AuditEvent.Escalation, T('Escalation')],
  [AuditEvent.Privileged, T('Privileged')],
  [AuditEvent.Export, T('Export')],
  [AuditEvent.Identity, T('Identity')],
  [AuditEvent.TimeChange, T('Time Change')],
  [AuditEvent.ModuleLoad, T('Module Load')],
  [AuditEvent.Service, T('Service')],
  [AuditEvent.TtyRecord, T('TTY Record')],
]);
