export enum CertificateCreateType {
  CreateAcme = 'CERTIFICATE_CREATE_ACME',
  CreateInternal = 'CERTIFICATE_CREATE_INTERNAL',
  Import = 'CERTIFICATE_CREATE_IMPORTED',
  ImportCsr = 'CERTIFICATE_CREATE_IMPORTED_CSR',
  CreateCsr = 'CERTIFICATE_CREATE_CSR',
}
