export enum ExtendedKeyUsages {
  ANY_EXTENDED_KEY_USAGE = 'ANY_EXTENDED_KEY_USAGE',
  CLIENT_AUTH = 'CLIENT_AUTH',
  CODE_SIGNING = 'CODE_SIGNING',
  EMAIL_PROTECTION = 'EMAIL_PROTECTION',
  OCSP_SIGNING = 'OCSP_SIGNING',
  SERVER_AUTH = 'SERVER_AUTH',
  TIME_STAMPING = 'TIME_STAMPING',
}
