export enum ReportingGraphName {
  Cpu = 'cpu',
  CpuTemp = 'cputemp',
  Disk = 'disk',
  DiskTemp = 'disktemp',
  Memory = 'memory',
  NetworkInterface = 'interface',
  NfsStat = 'nfsstat',
  NfsStatBytes = 'nfsstatbytes',
  Partition = 'df',
  Processes = 'processes',
  Swap = 'swap',
  SystemLoad = 'load',
  Target = 'ctl',
  Uptime = 'uptime',
  Ups = 'ups',
  ZfsArcRatio = 'arcratio',
  ZfsArcResult = 'arcresult',
  ZfsArcSize = 'arcsize',
}
