export enum TruenasConnectStatusReason {
  Disabled = 'TrueNAS Connect is disabled',
  ClaimTokenMissing = 'Waiting for claim token to be generated',
  RegistrationFinalizationWaiting = 'Waiting for registration with TrueNAS Connect to complete',
  RegistrationFinalizationFailed = 'Registration finalization failed',
  RegistrationFinalizationTimeout = 'Registration finalization timed out',
  RegistrationFinalizationSucess = 'Registration finalization successful',
  CertGenerationInProgress = 'Certificate generation is in progress',
  CertGenerationFailed = 'Certificate generation failed',
  CertGenerationSuccess = 'Certificate generation was successful',
  CertConfigurationFailure = 'Failed to configure certificate in system UI',
  CertRenewalInProgress = 'Certificate renewal is in progress',
  CertRenewalFailure = 'Failed to renew certificate',
  CertRenewalSuccess = 'Certificate renewal was successful',
  Configured = 'TrueNAS Connect is configured',
}

export enum TruenasConnectStatus {
  Disabled = 'DISABLED',
  ClaimTokenMissing = 'CLAIM_TOKEN_MISSING',
  RegistrationFinalizationWaiting = 'REGISTRATION_FINALIZATION_WAITING',
  RegistrationFinalizationFailed = 'REGISTRATION_FINALIZATION_FAILED',
  RegistrationFinalizationTimeout = 'REGISTRATION_FINALIZATION_TIMEOUT',
  RegistrationFinalizationSucess = 'REGISTRATION_FINALIZATION_SUCCESS',
  CertGenerationInProgress = 'CERT_GENERATION_IN_PROGRESS',
  CertGenerationFailed = 'CERT_GENERATION_FAILED',
  CertGenerationSuccess = 'CERT_GENERATION_SUCCESS',
  CertConfigurationFailure = 'CERT_CONFIGURATION_FAILURE',
  CertRenewalInProgress = 'CERT_RENEWAL_IN_PROGRESS',
  CertRenewalFailure = 'CERT_RENEWAL_FAILURE',
  CertRenewalSuccess = 'CERT_RENEWAL_SUCCESS',
  Configured = 'CONFIGURED',
}
