#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
yarn extract
yarn extract-ui-searchable-elements
yarn validate-translations
git add src/assets/i18n
git add src/assets/ui-searchable-elements.json
