name: Check Ticket
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  check-ticket:
    permissions:
      contents: read
    uses: iXsystems/ux-github-workflows/.github/workflows/check-ticket.yml@v1
