name: WebUI
on:
  push:
    branches:
      - master
    paths:
      - 'src/assets/i18n/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/assets/i18n/**'

jobs:
  install:
    name: Checkout and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare

  lint-translations:
    name: Validate translation strings
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare
      - name: Validate
        run: yarn run validate-translations
